sonar.projectKey=Arnaud Le Grand_Projet_7
sonar.organization=Arnaud Le Grand
sonar.host.url=https://sonarcloud.io

# Chemins vers les sources
sonar.sources=client/src,server/src
sonar.tests=client/src,server/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts

# Exclusions (fichiers générés, dépendances)
sonar.exclusions=**/node_modules/**,**/dist/**,**/prisma/**,client/vite.config.ts

# Rapports de couverture (générés par Vitest)
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8