input {
  # On peut recevoir les logs via HTTP depuis Node.js
  http {
    port => 8081
    codec => json
  }
}

filter {
  # Ici on peut ajouter des tags ou parser des données
  mutate {
    add_tag => [ "orion_crm_logs" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orion-logs-%{+YYYY.MM.dd}"
  }
  # Pour voir ce qui passe dans la console de logstash
  stdout { codec => rubydebug }
}